### ISSUE TITLE
Issue with posting price entries fro Sage50 

### ISSUE THREAD

**Issue by susaree** [Sage/SData-2.0#145]
I'm posting to sdata/accounts50/gcrm-/prices and getting a "POST operation failed - Exception has been thrown by the target of invocation

It seems like I'm missing some info in my request but I've been stuck on this for days and can't figure it out, about to give up tbh
Request:
<sdata:payload>
    <crm:price sdata:uuid="ba9bd275-e3ad-4372-b121-6f0e460d137d">
        <crm:active>true</crm:active>
        <crm:reference>1</crm:reference>
        <crm:status>confirmed</crm:status>
        <crm:customerSupplierFlag>Customer</crm:customerSupplierFlag>
        <crm:tradingAccount sdata:uuid="5580677e-cc30-46cb-84be-e16a463316a0"/>
         <crm:commodity sdata:uuid="3b01af63-3caa-4408-b843-f22841e60609" />
         <crm:pricelist sdata:uuid="7cb44807-de7d-42cb-a789-b7de2ebb7884" />
        <crm:unitOfMeasure xsi:nil="true" />
        <crm:location xsi:nil="true" />
        <crm:postalAddress xsi:nil="true" />
        <crm:currency>GBP</crm:currency>
        <crm:operatingCompanyCurrency>GBP</crm:operatingCompanyCurrency>
        <crm:operatingCompanyCurrencyExchangeRate>1.00</crm:operatingCompanyCurrencyExchangeRate>
        <crm:operatingCompanyCurrencyExchangeRateOperator>*</crm:operatingCompanyCurrencyExchangeRateOperator>
        <crm:operatingCompanyCurrencyExchangeRateDate xsi:nil="true" />
        <crm:decimalPlaces>2</crm:decimalPlaces>
        <crm:price>59.16</crm:price>
        <crm:includesTax>false</crm:includesTax>
        <crm:startDate xsi:nil="true" />
        <crm:endDate xsi:nil="true" />
        <crm:notes xsi:nil="true" />
    </crm:price>
</sdata:payload>

Response:

<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:http="http://schemas.sage.com/sdata/http/2008/1" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1">
    <sdata:severity>error</sdata:severity>
    <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
    <sdata:applicationCode />
    <sdata:message>POST operation failed - Exception has been thrown by the target of an invocation.

   at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostRecordRequest(SDOWorkspaceScope scope, ISDORecord record, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestHandler.OnPostRequest(IRequest request, FeedEntry feedEntry)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)</sdata:message>
    <sdata:stackTrace />
    <sdata:payloadPath />
</diagnosis>

**Comment by darroncockram** [comment]
POST operations against the prices endpoint are not supported by the Sage 50 Accounts adapter I'm afraid. If you issue a $schema request you will see that the prices resource kind is flagged as smCanPost="false".
