### ISSUE TITLE
POST operation failed - Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by bubblemedialtd** [Sage/SData-2.0#27]
We've just replicated a customer management portal from one site to another, which uses sData.
It is using PHP and the current request is to insert a salesOrder.
At site A, the requests work flawlessly. However, at site B, the requests are returning the following error. See payload and response below:

```
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.w3.org/2005/Atom">
<id/>
<title/>
<content/>
<sdata:payload>
<salesOrder xmlns="http://schemas.sage.com/crmErp/2008" sdata:uuid="9b0fa662-f8fd-486b-be9e-92eadd98adb3">
<date>2015-10-01</date>
<tradingAccount sdata:uuid="11da777a-6be5-4e9d-9b6e-c9e4b37839a0"></tradingAccount>
<salesOrderLines> <salesOrderLine>
<commodity sdata:uuid="b0d3a611-117a-4659-ae59-126ea8a3a26a"></commodity>
<text>BETA 00010320028 1032-300 INTERNAL CIRCLIP PLIERS (00010320028)</text>
<actualPrice>27.00</actualPrice>
<initialPrice>27</initialPrice>
<netTotal>27</netTotal>
<taxTotal>5.4</taxTotal>
<quantity>1</quantity>
</salesOrderLine></salesOrderLines>
</salesOrder>
</sdata:payload>
</entry>
```

Response:

```
 <?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
 <sdata:severity>error</sdata:severity>
 <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
 <sdata:applicationCode />
 <sdata:message>POST operation failed - Exception has been thrown by the target of an invocation.

 at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandle&amp; ctor, Boolean&amp; bNeedSecurityCheck)
 at System.Activator.CreateInstance[T]()
 at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReferenceElement[S,T](XmlReader reader, T component, ISerializationSettings settings)
 at ObjectXmlReaderf5d5d792f93b4d4a924616191b05867e.dll.ReadElement(XmlReader , Object , Int32 , ISerializationSettings )
 at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReference[T](XmlReader reader, T component, String name, ISerializationSettings settings)
 at ObjectXmlReaderf5d5d792f93b4d4a924616191b05867e.dll.Deserialize(XmlReader , Object , String , ISerializationSettings )
 at Sage.Common.Metadata.RuntimeObjectXmlReader.Deserialize(XmlReader reader, Object component, String name)
 at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](T feedEntry, Stream stream, ISerializationSettings settings, String assemblyFileLocation)
 at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](T feedEntry, Stream stream, ISerializationSettings settings)
 at RuntimeRequestHandlerbbd96f50dcc14bdc814b50451f728f43.LoadFeedEntryFromStream(IFeedSerializer , FeedEntry , Stream )
 at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.LoadFeedEntryFromStream(IFeedSerializer serializer, FeedEntry feedEntry, Stream stream)
 at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
 at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
 at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)</sdata:message>
 <sdata:stackTrace />
 <sdata:payloadPath />
</diagnosis>
```

**Comment by darroncockram** [comment]
Is the XML above definitely from a failing request? The error message would indicate an error in the XML that is being posted but I have tested posting the XML quoted above and get no error with it.

**Comment by bubblemedialtd** [comment]
Hi Darron,

Yes, the above XML is from a failing request. We've tried other requests too, which all yield the same error. Yet, if we perform it on site A, it works perfectly.

**Comment by darroncockram** [comment]
So I guess the question would be what's the difference(s) between site A and site B?

**Comment by bubblemedialtd** [comment]
That is a good question, in terms of software - there is no difference whatsoever. Other than they are 2 different Sage companies.

We have created a new VM and installed Sage 50 on there and restored a backup, the same issue exists.

**Comment by bubblemedialtd** [comment]
To eliminate the 3rd party CMP built in PHP, I have been using PostMan on Chrome to submit POST requests, the same issue exists.

**Comment by darroncockram** [comment]
So just to be clear, if you POST the **exact** same XML to both sites we are saying that site A will successfully create a salesOrder but site B returns the error?
When you say they are two different Sage companies does this mean 2 different datasets on the same installation or two entirely separate installations?

**Comment by lstyles** [comment]
I've been experiencing the same issue and it came down to password being in uppercase (accepted by Sage Desktop Application). 

Once I changed the password to all lowercase it started working.
