### ISSUE TITLE
GET operation failed - ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#37]
When attempting to perform a GET request using Sage 50 Accounts a "500 Internal Server Error" error occurs with the below message.  Can you please help identify the cause and how this issue can be fixed?

The GET request is: GET /sdata/accounts50/GCRM/{30DAA503-C4AD-4117-8EB4-A8CA2C7CE1DB}/tradingAccounts 

<sdata:message>GET operation failed - ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetWorkspace(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceScope..ctor(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.Feeds.Company.GetActiveCompany()
   at Sage.Integration.Accounts50.SDOAdapter.Feeds.tradingAccountFeed..ctor()
   at RuntimeRequestHandler3a03d20a756a465fb8218def9eb7c56c.CreateFeedInstance()
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.CreateFeedInstance()
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)</sdata:message>

**Comment by darroncockram** [comment]
From that error I'd guess that the version of the data does not match with an installed version of Accounts (or at least the ODBC driver). What version is the data (you can see the data version in the select company screen in the main Accounts applicaiton)?

**Comment by geoffo** [comment]
The Sage 50 version is v21 SP5. The data for this error was created in that version of Sage, so it can't be mismatched with the app. On the Select Company screen it says v21. How do I check the pedigree of my ODBC driver?

**Comment by darroncockram** [comment]
If you're on v21 there's a couple of things you could check around the ODBC driver. Firstly do you have the file S21DBC32.dll in your C:\Windows\SysWOW64 folder? If you do is there a valid system DSN called SageLine50v21 configured? You can check the latter via the ODBC data source admin tool in Windows - C:\Windows\SysWOW64\odbcad32.exe

NOTE: I'm assuming a 64-bit version of Windows here.

One other thing to check. Do you get the same problem if you create an new v21 dataset and query that via Sdata?

**Comment by darroncockram** [comment]
Closing issue as no response.
