### ISSUE TITLE
Sage 50 Accounts - 500 Internal Server Error - 80070583

### ISSUE THREAD

**Issue by geoffo** [Sage/SData-2.0#65]
When trying to query the TradingAccounts endpoint, we are seeing a 500 Internal Server error.  The error in the response says: "GET operation failed - Retrieving the COM class factory for component with CLSID {32F9466C-D217-481E-933C-C898F8D9A9D4} failed due to the following error: 80070583."  Do you have any idea what causes this error and what is required to fix it?

```
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <sdata:severity>error</sdata:severity>
  <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
  <sdata:applicationCode />
  <sdata:message>GET operation failed - Retrieving the COM class factory for component with CLSID {32F9466C-D217-481E-933C-C898F8D9A9D4} failed due to the following error: 80070583.

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandle&amp; ctor, Boolean&amp; bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean fillCache)
   at System.RuntimeType.CreateInstanceImpl(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetEngine(Byte version)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceManager.GetWorkspace(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDOWorkspaceScope..ctor(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.Feeds.Company.GetActiveCompany()
   at Sage.Integration.Accounts50.SDOAdapter.Feeds.tradingAccountFeed..ctor()
   at RuntimeRequestHandlerd375c6dc69d74860835a6bbacbd52e19.CreateFeedInstance()
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.CreateFeedInstance()
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnGetRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.GetRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.OnGetResource(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.GetRequest(IRequest request) (-1)</sdata:message>
  <sdata:stackTrace />
  <sdata:payloadPath />
</diagnosis>
```

**Comment by darroncockram** [comment]
From the error it suggests that the service is trying to connect to a version of the data files for which it can't find a matching version of SDO, or possibly that there is in install issue with that version of SDO. What version of the data files are you trying to connect to?

**Comment by darroncockram** [comment]
Closed as no response.
