### ISSUE TITLE
POST operation failed - Invalid payload detected

### ISSUE THREAD

**Issue by Myddleware** [Sage/SData-2.0#95]
Hi,
I try to create a contact into Sage50 and I get this error : POST operation failed - Invalid payload detected, expecting 'contact' found 'http://schemas.sage.com/GCRM:contact'

Here is the xml I send to Sage: 
```
<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.w3.org/2005/Atom">
  <id/>
  <title/>
  <content/>
  <sdata:payload>
    <contact xmlns="http://schemas.sage.com/GCRM"
      sdata:uuid="5f77e8f8-747b-48d9-bf94-bb9ca25d6d56">
      <familyName>Doe</familyName>
      <firstName>John</firstName>
      <notes>Sage test</notes>
      <reference>999</reference>
    </contact>
  </sdata:payload>
</entry>
```

Here is the full error I get : 
```
<?xml version="1.0" encoding="utf-8"?>
<diagnosis xmlns="http://schemas.sage.com/sdata/2008/1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sdatasync="http://schemas.sage.com/sdata/sync/2008/1" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sdata="http://schemas.sage.com/sdata/2008/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:sme="http://schemas.sage.com/sdata/sme/2007" xmlns:http="http://schemas.sage.com/sdata/http/2008/1">
  <sdata:severity>error</sdata:severity>
  <sdata:sdataCode>ApplicationDiagnosis</sdata:sdataCode>
  <sdata:applicationCode />
  <sdata:message>POST operation failed - Invalid payload detected, expecting 'contact' found 'http://schemas.sage.com/GCRM:contact'.

   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadStartGroup(XmlReader reader, String name, String type, String ns, Int32 internalCount, String detachedPayloadProperty)
   at Sage.Common.Metadata.RuntimeObjectXmlReader.ReadReference[T](XmlReader reader, T component, String name, ISerializationSettings settings)
   at ObjectXmlReader67e387c4ceb84a2d92fca5d441403147.dll.Deserialize(XmlReader , Object , String , ISerializationSettings )
   at Sage.Common.Metadata.RuntimeObjectXmlReader.Deserialize(XmlReader reader, Object component, String name)
   at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](T feedEntry, Stream stream, ISerializationSettings settings, String assemblyFileLocation)
   at Sage.Common.Syndication.FeedSerializer.LoadFromStream[T](T feedEntry, Stream stream, ISerializationSettings settings)
   at RuntimeRequestHandler666f6c0185c34baa94c9cfad2f9eaef3.LoadFeedEntryFromStream(IFeedSerializer , FeedEntry , Stream )
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.LoadFeedEntryFromStream(IFeedSerializer serializer, FeedEntry feedEntry, Stream stream)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.OnPostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.RequestHandler`2.PostRequest(IRequest request)
   at Sage.Integration.Accounts50.SDOAdapter.SDORequestManager.PostRequest(IRequest request) (-1)</sdata:message>
  <sdata:stackTrace />
  <sdata:payloadPath />
</diagnosis>
```

I used this page to build the xml : http://sage.github.io/SData-2.0/pages/core/0801/

Do you know what is my mistake ? Thanks
Have a nice day.

**Comment by darroncockram** [comment]
The POST is failing because the namespace on your contact payload is not valid. GCRM is the contract, rather than the schema namespace. You'll need to use a valid namespace e.g.

```XML
<contact xmlns="http://schemas.sage.com/crmErp/2008">
```
In addition to this there are a few other issues I can see with your payload that will mean your request will fail even if you fix the namespace issue.

1. The notes property is a complex type so you cannot set it to a string. It would have to be a valid feed of notes. Having said that the notes property is flagged as sme:unsupported="true" in the schema for the Sage 50 Accounts adapter so this means it will not be processed even if a valid feed of notes is supplied.

2. In Sage 50 Accounts contacts cannot exist independently of other 'parent' objects (customers, suppliers, invoices, etc) but there is no context of what type of parent the contact belongs to. You would need to specify the type property of the contact to give the necessary context e.g.

```XML
<type>Customer Delivery Contact</type>
```
3. Further to the above point about the type of parent the contact belongs to you also need to give context of which specific entity is the parent. For this would need to specify the UUID of the parent in the appropriate property e.g.

```XML
<tradingAccount sdata:uuid="be33197f-03c1-46e3-b789-5e078562b0c0" />
```

**Comment by Myddleware** [comment]
Hi Darroncockram,
It works ! Thanks so much for your help and your reactivity. 

If someone else has the same problem, here is the xml I have successfully sent : 
```
<?xml version="1.0" encoding="utf-8"?>
<entry xmlns:sdata="http://schemas.sage.com/sdata/2008/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.w3.org/2005/Atom">
  <id/>
  <title/>
  <content/>
  <sdata:payload>
    <contact xmlns="http://schemas.sage.com/crmErp/2008">
      <familyName>Doe</familyName>
      <firstName>John</firstName>
      <tradingAccount sdata:uuid="c10e13ab-1403-4a2d-b8bc-c4ddf2f46daf" />
      <type>Customer Delivery Contact</type>
    </contact>
  </sdata:payload>
</entry>
```
Have a nice day.
